language: ruby
rvm:
- 2.6.1

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

# Enable caching on TravisCI
cache:
  bundler: true
  directories:
  - $TRAVIS_BUILD_DIR/tmp/.htmlproofer

addons:
  apt:
    packages:
    - libcurl4-openssl-dev # required to avoid SSL errors

install:
- bundle install
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: _site
  target_branch: master
  on:
    branch: source
