language: ruby

# Keep Travis from testing `master` branch
branches:
  except:
  - master

# Deployment config
deploy:
  provider: script
  script: "./_scripts/build.sh"
  skip_cleanup: false
  on:
    branch: source

env:
  global:
  - secure: izGxYkC27UpZjY2ZMipD1YFneE8aNxZF9MbBrE+H6JNvJz+pyjSN489znnnlbNsQ4z5yFyCOznIuMaI0dTxfJU3Q6fQU/wWSN5o1PZS7xXVZi6Kz/pRhdolAD9D80GAIQNHjyx4h6hw/1CvLCV+L2G+NjAtwXRcVAEun5TfSzTo+ryU+xb3HCe+6DCcBq3FcpkxNncce0cVsdKa2IRd9nlw7Qgu1wt+MgnLxgPeCXFrv+qWJUkr90AcAbBP0dfWqqONbNUCMmj+t5Ga3COW6RFbey2z5S4cDAYj4mYR/kgvJqycWcGxWs6znwQbiI6pzT27VBtu6B9ginOzCqc8Y6Qwzk+yygkeDZSReFElWnpma34sqvHaBp3UkR2mjZR2u/QpI2G65+y0sSRRt+TwyFsaUp34XBqORlcK53DfBvUnx4cef/2AQEV7hIIGx4ui0EsWDNnz0HttC5/MKBPsTPXeNZuNxBRv1EsDkg90pvG0zopsasptNRspqvpWdczoTiIyIn9UA2PYV64eCF4+wpzQb8gRV1/N0Vrw3W3W2fbxW1X6NZuqxi/Wg+cPxeR1eSe6mIulvDXB+vu/1MpunSqfkV5uUd9vU/b/4MusMlyDC9qOV5rTg7Y5UHsMAqEtR/rM2L9Sftllp562eRTzCPUEutH7qqz94S6CWQZFqU6I=
  - secure: Ms9Gct5oiqMzZVn4W2enghOAaOs8INl/DHLSZt2+k0rwATpHn8cyWtc79Fe9mmrxwhWflfNnbLnWQ2nrqGhJWlnWLui6TqddciuOowvmk0hEODYiULiByzAtbDP8ntV8HdVSVCtkIiR98BBdLCyIZ2VzjOuENZMuy/n5ypoa1gI8qD0HKPfBC2IylY43xaWgyua4gXRiMobL5s6su+4KR/agjQKzhlFQ5WrLqKVKizsNb3/KXssUcDQX/aeVPeIMjkyH2D+A02WFDzH9pSt75cYRQUO/7Lqsg/zGd3kks72xlYBM4zf3CAn+BlrM7QkRayvgxdp1vMvYEialZ2h6GRUlb38mRbqDKXOkcZ6mDsUPVOYxLZc9NgpmqYNLO0tj+C2jK7/s1W/+1FDzBTQOKV6kI4vZocjgWn88rsljoeZLsqJiF5QwIgHtw8IyALrFps6x2X7+rdnxaEDEdONZBj2yiTK4TjRpoRr5JG3/40oQ0r97MKBzIM6DFL6Dt8vnJZsEXv2Wtfx2Z5VzTUFb7Xb9YaAusZAMCBn5hu493XANecn9XD4VZrwm4JdJ1RqOM01wdTtvuHJWFb0h7gqqJ3zXFzOGxrwohprXB4gM9uoSstI1GvnMOhDyQeQNBiYlRW83T+eVgzEmxpk5VmIDvAVrQaRDMhSEg8zILuFBXkg=
