language: ruby
rvm:
- 2.3.1
sudo: required
before_install:
  - sudo update-ca-certificates
install:
- bundle install
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: _site
  target_branch: master
  on:
    branch: source
