# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Software Engineering Simplified
email: joshmfrankel@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: joshmfrankel
github_username:  joshmfrankel

# Structure Settings
permalink: /:year/:title/
excerpt_separator: "--excerpt--"
paginate: 10

# Build Settings
sass:
  style: compact
  sass_dir: _sass
github: [metadata]
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Theme styles
theme: minima

# Gemfile
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
