# Base Settings
title: Development Simplified
email: joshmfrankel@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog about ruby, sql, performance, and patterns.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
twitter_username: joshmfrankel
github_username:  joshmfrankel

# Structure Settings
permalink: /:year/:title/
excerpt_separator: "--excerpt--"
paginate: 10
github: [metadata]
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM

# Build Settings
sass:
  style: compact
  sass_dir: _sass

# Gemfile
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
