# This is a basic workflow to help you get started with Actions

name: Jekyll Deployment

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the source branch
on:
  push:
    branches: [ source ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1

      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install Dependencies
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Build Site
        run: JEKYLL_ENV=production bundle exec jekyll build -d docs

      - name: Run HTMLProofer
        run: bundle exec htmlproofer "./docs" --check-opengraph --check-favicon --http_status_ignore "999" --typhoeus-config "{\"ssl_verifypeer\":false}" --url-ignore "/twitter\.com.*|quickleft\.com.*|globalnerdy.com.*|http:\/\/joshfrankel.me\/blog\/.*$/"

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      # Start new branch without history
      # Remove all cached history
      # Relocate .git tracking to publishable folder
      # Navigate into publishable folder
      - name: Deployment
        run: |
          [ -z "$(git show-ref gh-pages)" ] && git checkout -b gh-pages || git checkout gh-pages
          git add docs/
          git commit -m "Deployment - $(TZ=":US/Eastern" date +"%A %b %d, %Y at %I:%M %p")"
          git push origin gh-pages
